spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: mysql
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.czj.webdemo.modules.cc

server.port: 8083
